IF EXISTS (SELECT NAME FROM sysobjects WHERE NAME = 'POP3EmailAccount' AND TYPE = 'U')
DROP TABLE POP3EmailAccount;
GO

IF EXISTS (SELECT NAME FROM sysobjects WHERE NAME = 'POP3EmailAccount' AND TYPE = 'U')
	DROP TABLE POP3EmailAccount;
GO

CREATE TABLE POP3EmailAccount
(
	POP3EmailAccountID		IDENTITY (1001,1) INT  NOT NULL,
	UserID		 INT  NOT NULL,
	POP3EmailAccountName		 VARCHAR(50)  NOT NULL,
	Active		 BIT DEFAULT ((1)) NOT NULL,
	create_dt		 DATETIME DEFAULT (getdate()) NOT NULL

);
GO




GO


GO

