IF EXISTS (SELECT NAME FROM sysobjects WHERE NAME = 'sp_administration_reindex' AND TYPE = 'P')
DROP PROCEDURE sp_administration_reindex;
GO


CREATE PROCEDURE [dbo].[sp_administration_reindex]
AS
	DECLARE @SQL 		VARCHAR(1000)
	DECLARE @TABLE_NAME 	VARCHAR(20)

	DECLARE TABLES_CURSOR CURSOR FOR 
		SELECT NAME FROM SYSOBJECTS WHERE TYPE = 'U' AND NAME <> 'dtproperties' ORDER BY NAME

	OPEN TABLES_CURSOR
	FETCH NEXT FROM TABLES_CURSOR INTO @TABLE_NAME

	WHILE @@FETCH_STATUS = 0
		BEGIN
			SET @SQL = 'DBCC DBREINDEX (''' + @TABLE_NAME + ''');'
			PRINT @SQL
			EXEC(@SQL)
			FETCH NEXT FROM TABLES_CURSOR INTO @TABLE_NAME
		END

	CLOSE TABLES_CURSOR
	DEALLOCATE TABLES_CURSOR




GO

