IF EXISTS (SELECT NAME FROM sysobjects WHERE NAME = 'sp_CreditCard_delete' AND TYPE = 'P')
DROP PROCEDURE sp_CreditCard_delete;
GO


CREATE PROCEDURE [dbo].[sp_CreditCard_delete]
	@CCID	INT
AS
	BEGIN TRANSACTION
		DELETE FROM CCBALANCE WHERE CCID = @CCID;
		IF @@ERROR <> 0 ROLLBACK TRANSACTION
		DELETE FROM CREDITCARD WHERE CreditCardID = @CCID;
		IF @@ERROR <> 0 ROLLBACK TRANSACTION
	COMMIT TRANSACTION


GO

