IF EXISTS (SELECT NAME FROM sysobjects WHERE NAME = 'sp_DeleteUser' AND TYPE = 'P')
DROP PROCEDURE sp_DeleteUser;
GO


CREATE PROCEDURE [dbo].[sp_DeleteUser] 
	@UserID	INT
AS

	BEGIN TRANSACTION
		DELETE FROM Companies WHERE UserID = @UserID;
		IF @@ERROR <> 0 ROLLBACK TRANSACTION
		DELETE FROM CreditCard  WHERE UserID = @UserID;
		IF @@ERROR <> 0 ROLLBACK TRANSACTION
		DELETE FROM Logins WHERE UserID = @UserID;
		IF @@ERROR <> 0 ROLLBACK TRANSACTION
		DELETE FROM Users WHERE UserID = @UserID;
		IF @@ERROR <> 0 ROLLBACK TRANSACTION
	COMMIT TRANSACTION

GO

