USE TCM;
GO


ALTER TABLE Member ALTER COLUMN Address1 VARCHAR(50) NULL;
GO
ALTER TABLE Member ALTER COLUMN City VARCHAR(50) NULL;
GO
ALTER TABLE Member ALTER COLUMN [State] CHAR(2) NULL;
GO
ALTER TABLE Member ALTER COLUMN Zip VARCHAR(12) NULL;
GO
ALTER TABLE Member ALTER COLUMN Phone1 VARCHAR(50) NULL;
GO
ALTER TABLE Member ALTER COLUMN Cell VARCHAR(50) NULL;
GO
ALTER TABLE Member ALTER COLUMN Cell2 VARCHAR(50) NULL;
GO
ALTER TABLE Member ALTER COLUMN Grade INT NULL;
GO
