<?xml version="1.0" encoding="utf-8"?><Database Name="TCM" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQL2K8;Initial Catalog=TCM;Persist Security Info=True;User ID=TCM_user@iulclqxig0" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TCMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Member" Member="Members">
    <Type Name="Member">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ResourceName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreateUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Salutation" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="ScreenName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="Province" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone2" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cell" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cell2" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email1" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Email2" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ImageId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="OriginalImageUrl" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="StatusMessage" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Dob" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IdNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Aka" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Grade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="MustChangePassword" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CustomField1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomField2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FamilyCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Member_School_StudentMember" Member="School_StudentMembers" ThisKey="Id" OtherKey="StudentMemberId" Type="School_StudentMember" />
      <Association Name="Member_Member_School" Member="Member_Schools" ThisKey="Id" OtherKey="MemberId" Type="Member_School" />
    </Type>
  </Table>
  <Table Name="dbo.School" Member="Schools">
    <Type Name="School">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="School_School_StudentMember" Member="School_StudentMembers" ThisKey="Id" OtherKey="SchoolId" Type="School_StudentMember" />
      <Association Name="School_Member_School" Member="Member_Schools" ThisKey="Id" OtherKey="SchoolId" Type="Member_School" />
    </Type>
  </Table>
  <Table Name="dbo.School_StudentMember" Member="School_StudentMembers">
    <Type Name="School_StudentMember">
      <Column Name="SchoolId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StudentMemberId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Member_School_StudentMember" Member="Member" ThisKey="StudentMemberId" OtherKey="Id" Type="Member" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="School_School_StudentMember" Member="School" ThisKey="SchoolId" OtherKey="Id" Type="School" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Member_School" Member="Member_Schools">
    <Type Name="Member_School">
      <Column Name="MemberId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SchoolId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Member_Member_School" Member="Member" ThisKey="MemberId" OtherKey="Id" Type="Member" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="School_Member_School" Member="School" ThisKey="SchoolId" OtherKey="Id" Type="School" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Member_Logs" Member="Member_Logs">
    <Type Name="Member_Log">
      <Column Name="Member_LogsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameSpaceName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MethodName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ExceptionMessage" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ExceptionString" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="create_dt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.sp_Member_insert" Method="sp_Member_insert">
    <Parameter Name="UserID" Parameter="userID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="SchoolID" Parameter="schoolID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Address1" Parameter="address1" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="State" Parameter="state" Type="System.String" DbType="Char(2)" />
    <Parameter Name="Zip" Parameter="zip" Type="System.String" DbType="VarChar(12)" />
    <Parameter Name="Phone1" Parameter="phone1" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Cell" Parameter="cell" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Cell2" Parameter="cell2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Dob" Parameter="dob" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FamilyCode" Parameter="familyCode" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_Member_insertResult">
      <Column Name="MemberID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Member_Logs_insert" Method="sp_Member_Logs_insert">
    <Parameter Name="NameSpaceName" Parameter="nameSpaceName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ClassName" Parameter="className" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="MethodName" Parameter="methodName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ExceptionMessage" Parameter="exceptionMessage" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="ExceptionString" Parameter="exceptionString" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Comments" Parameter="comments" Type="System.String" DbType="VarChar(MAX)" />
  </Function>
</Database>