
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<html class="no-js" lang="en">
<head>
	<title>Theodore Tirado - www.tiradoonline.com</title>

	<meta charset="UTF-8" />
	<meta name="description" content="Theodore Tirado" />
	<meta name="keywords" content="
		HTML, CSS, XML, JavaScript Programmer, Web Developer
	" />
	<meta name="author" content="Theodore Tirado" />
	<meta name="viewport" content="width=device-width, intial-scale=1.0" />
	<link rel="icon" type="image/ico" href="/images/icons/logo.ico" /> 
	<link rel="shortcut icon" href="/images/icons/logo.ico" />
	
    <script src="/includes/jquery/jquery.js" type="text/javascript"></script>
	<link type="text/css" rel="stylesheet" href="/includes/foundation/css/foundation.css" />
	<!-- #include virtual="/includes/css/global.css" -->	
	<!-- #include virtual="/includes/js/functions.js" -->	
	
</head>

<body leftmargin="0" topmargin="0" rightmargin="0" bottommargin="0" marginwidth="0" marginheight="0">


<!-- #include virtual="/includes/navigation.inc" -->	


<div class="row">

  <div class="small-6 large-centered columns container">
  
  	<!-- ******************** -->
	
	<!--   MIDDLE COLUMN -->

  	<!-- ******************** -->
  
