#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pop3Application
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="tiradoonline")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBDataContext() : 
				base(global::Pop3Application.Properties.Settings.Default.tiradoonlineConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_POP3Email_get")]
		public ISingleResult<sp_POP3Email_getResult> sp_POP3Email_get([global::System.Data.Linq.Mapping.ParameterAttribute(Name="POP3EmailID", DbType="Int")] System.Nullable<int> pOP3EmailID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pOP3EmailID);
			return ((ISingleResult<sp_POP3Email_getResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_POP3Email_insert")]
		public int sp_POP3Email_insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="POP3EmailFolderID", DbType="Int")] System.Nullable<int> pOP3EmailFolderID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="POP3EmailMessageID", DbType="VarChar(100)")] string pOP3EmailMessageID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="POP3EmailMessageDateTime", DbType="DateTime")] System.Nullable<System.DateTime> pOP3EmailMessageDateTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="POP3EmailFromName", DbType="VarChar(500)")] string pOP3EmailFromName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="POP3EmailFromEmail", DbType="VarChar(500)")] string pOP3EmailFromEmail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="POP3EmailSubject", DbType="VarChar(500)")] string pOP3EmailSubject, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="POP3EmailBodyText", DbType="VarChar(MAX)")] string pOP3EmailBodyText)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pOP3EmailFolderID, pOP3EmailMessageID, pOP3EmailMessageDateTime, pOP3EmailFromName, pOP3EmailFromEmail, pOP3EmailSubject, pOP3EmailBodyText);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class sp_POP3Email_getResult
	{
		
		private int _POP3EmailID;
		
		private int _POP3EmailFolderID;
		
		private string _POP3EmailMessageID;
		
		private System.Nullable<System.DateTime> _POP3EmailMessageDateTime;
		
		private string _POP3EmailFromName;
		
		private string _POP3EmailFromEmail;
		
		private string _POP3EmailSubject;
		
		private string _POP3EmailBodyText;
		
		private bool _Active;
		
		private System.Nullable<System.DateTime> _create_dt;
		
		public sp_POP3Email_getResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POP3EmailID", DbType="Int NOT NULL")]
		public int POP3EmailID
		{
			get
			{
				return this._POP3EmailID;
			}
			set
			{
				if ((this._POP3EmailID != value))
				{
					this._POP3EmailID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POP3EmailFolderID", DbType="Int NOT NULL")]
		public int POP3EmailFolderID
		{
			get
			{
				return this._POP3EmailFolderID;
			}
			set
			{
				if ((this._POP3EmailFolderID != value))
				{
					this._POP3EmailFolderID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POP3EmailMessageID", DbType="VarChar(100)")]
		public string POP3EmailMessageID
		{
			get
			{
				return this._POP3EmailMessageID;
			}
			set
			{
				if ((this._POP3EmailMessageID != value))
				{
					this._POP3EmailMessageID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POP3EmailMessageDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> POP3EmailMessageDateTime
		{
			get
			{
				return this._POP3EmailMessageDateTime;
			}
			set
			{
				if ((this._POP3EmailMessageDateTime != value))
				{
					this._POP3EmailMessageDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POP3EmailFromName", DbType="VarChar(500)")]
		public string POP3EmailFromName
		{
			get
			{
				return this._POP3EmailFromName;
			}
			set
			{
				if ((this._POP3EmailFromName != value))
				{
					this._POP3EmailFromName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POP3EmailFromEmail", DbType="VarChar(500)")]
		public string POP3EmailFromEmail
		{
			get
			{
				return this._POP3EmailFromEmail;
			}
			set
			{
				if ((this._POP3EmailFromEmail != value))
				{
					this._POP3EmailFromEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POP3EmailSubject", DbType="VarChar(500)")]
		public string POP3EmailSubject
		{
			get
			{
				return this._POP3EmailSubject;
			}
			set
			{
				if ((this._POP3EmailSubject != value))
				{
					this._POP3EmailSubject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POP3EmailBodyText", DbType="VarChar(MAX)")]
		public string POP3EmailBodyText
		{
			get
			{
				return this._POP3EmailBodyText;
			}
			set
			{
				if ((this._POP3EmailBodyText != value))
				{
					this._POP3EmailBodyText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_dt", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_dt
		{
			get
			{
				return this._create_dt;
			}
			set
			{
				if ((this._create_dt != value))
				{
					this._create_dt = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
