#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryNameSpace
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="tiradoonline")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBDataContext() : 
				base(global::ClassLibraryNameSpace.Properties.Settings.Default.tiradoonlineConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Banking_BankingAccountID_BankingDate_get")]
		public ISingleResult<sp_Banking_BankingAccountID_BankingDate_getResult> sp_Banking_BankingAccountID_BankingDate_get([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankingAccountID", DbType="Int")] System.Nullable<int> bankingAccountID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BankingDate", DbType="SmallDateTime")] System.Nullable<System.DateTime> bankingDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bankingAccountID, bankingDate);
			return ((ISingleResult<sp_Banking_BankingAccountID_BankingDate_getResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BankingAccount_active_get")]
		public ISingleResult<sp_BankingAccount_active_getResult> sp_BankingAccount_active_get([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Active", DbType="Bit")] System.Nullable<bool> active, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Administrator", DbType="Bit")] System.Nullable<bool> administrator)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, active, administrator);
			return ((ISingleResult<sp_BankingAccount_active_getResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BankingAccount_ReceiveEmail_get")]
		public ISingleResult<sp_BankingAccount_ReceiveEmail_getResult> sp_BankingAccount_ReceiveEmail_get([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] System.Nullable<int> userID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID);
			return ((ISingleResult<sp_BankingAccount_ReceiveEmail_getResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Logs_insert")]
		public int sp_Logs_insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplicationName", DbType="VarChar(1000)")] string applicationName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LogDesc", DbType="VarChar(MAX)")] string logDesc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), applicationName, logDesc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Timesheet_TimesheetID_get")]
		public ISingleResult<sp_Timesheet_TimesheetID_getResult> sp_Timesheet_TimesheetID_get([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimesheetID", DbType="Int")] System.Nullable<int> timesheetID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), timesheetID);
			return ((ISingleResult<sp_Timesheet_TimesheetID_getResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_Banking_BankingAccountID_BankingDate_getResult
	{
		
		private int _BankingID;
		
		private System.Nullable<int> _BankingAccountID;
		
		private System.Nullable<int> _SubBankingAccountID;
		
		private string _BankingAccountName;
		
		private string _SubAccountName;
		
		private System.DateTime _BankingDate;
		
		private decimal _Payment;
		
		private string _Comment;
		
		private string _Description;
		
		private bool _BankingFile;
		
		private string _BankingFileName;
		
		public sp_Banking_BankingAccountID_BankingDate_getResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankingID", DbType="Int NOT NULL")]
		public int BankingID
		{
			get
			{
				return this._BankingID;
			}
			set
			{
				if ((this._BankingID != value))
				{
					this._BankingID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankingAccountID", DbType="Int")]
		public System.Nullable<int> BankingAccountID
		{
			get
			{
				return this._BankingAccountID;
			}
			set
			{
				if ((this._BankingAccountID != value))
				{
					this._BankingAccountID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubBankingAccountID", DbType="Int")]
		public System.Nullable<int> SubBankingAccountID
		{
			get
			{
				return this._SubBankingAccountID;
			}
			set
			{
				if ((this._SubBankingAccountID != value))
				{
					this._SubBankingAccountID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankingAccountName", DbType="VarChar(50)")]
		public string BankingAccountName
		{
			get
			{
				return this._BankingAccountName;
			}
			set
			{
				if ((this._BankingAccountName != value))
				{
					this._BankingAccountName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubAccountName", DbType="VarChar(50)")]
		public string SubAccountName
		{
			get
			{
				return this._SubAccountName;
			}
			set
			{
				if ((this._SubAccountName != value))
				{
					this._SubAccountName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankingDate", DbType="SmallDateTime NOT NULL")]
		public System.DateTime BankingDate
		{
			get
			{
				return this._BankingDate;
			}
			set
			{
				if ((this._BankingDate != value))
				{
					this._BankingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment", DbType="Decimal(8,2) NOT NULL")]
		public decimal Payment
		{
			get
			{
				return this._Payment;
			}
			set
			{
				if ((this._Payment != value))
				{
					this._Payment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="VarChar(255)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(1000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankingFile", DbType="Bit NOT NULL")]
		public bool BankingFile
		{
			get
			{
				return this._BankingFile;
			}
			set
			{
				if ((this._BankingFile != value))
				{
					this._BankingFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankingFileName", DbType="VarChar(200)")]
		public string BankingFileName
		{
			get
			{
				return this._BankingFileName;
			}
			set
			{
				if ((this._BankingFileName != value))
				{
					this._BankingFileName = value;
				}
			}
		}
	}
	
	public partial class sp_BankingAccount_active_getResult
	{
		
		private int _BankingAccountID;
		
		private string _FullName;
		
		private string _BankingAccountName;
		
		private System.Nullable<decimal> _Balance;
		
		private bool _ReceiveEmails;
		
		private int _UserID;
		
		public sp_BankingAccount_active_getResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankingAccountID", DbType="Int NOT NULL")]
		public int BankingAccountID
		{
			get
			{
				return this._BankingAccountID;
			}
			set
			{
				if ((this._BankingAccountID != value))
				{
					this._BankingAccountID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(84)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankingAccountName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BankingAccountName
		{
			get
			{
				return this._BankingAccountName;
			}
			set
			{
				if ((this._BankingAccountName != value))
				{
					this._BankingAccountName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiveEmails", DbType="Bit NOT NULL")]
		public bool ReceiveEmails
		{
			get
			{
				return this._ReceiveEmails;
			}
			set
			{
				if ((this._ReceiveEmails != value))
				{
					this._ReceiveEmails = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
	}
	
	public partial class sp_BankingAccount_ReceiveEmail_getResult
	{
		
		private int _BankingAccountID;
		
		private string _FullName;
		
		private string _Email;
		
		private string _BankingAccountName;
		
		private System.Nullable<decimal> _Balance;
		
		private bool _ReceiveEmails;
		
		private int _UserID;
		
		public sp_BankingAccount_ReceiveEmail_getResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankingAccountID", DbType="Int NOT NULL")]
		public int BankingAccountID
		{
			get
			{
				return this._BankingAccountID;
			}
			set
			{
				if ((this._BankingAccountID != value))
				{
					this._BankingAccountID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(84)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankingAccountName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BankingAccountName
		{
			get
			{
				return this._BankingAccountName;
			}
			set
			{
				if ((this._BankingAccountName != value))
				{
					this._BankingAccountName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiveEmails", DbType="Bit NOT NULL")]
		public bool ReceiveEmails
		{
			get
			{
				return this._ReceiveEmails;
			}
			set
			{
				if ((this._ReceiveEmails != value))
				{
					this._ReceiveEmails = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
	}
	
	public partial class sp_Timesheet_TimesheetID_getResult
	{
		
		private int _TimesheetID;
		
		private int _TimesheetCompanyID;
		
		private System.DateTime _TimesheetInvoiceDate;
		
		private string _TimesheetInvoiceNumber;
		
		private decimal _TimesheetHourlyRate;
		
		private System.DateTime _TimesheetStartDate;
		
		private System.DateTime _TimesheetEndDate;
		
		private string _TimesheetHTML;
		
		private bool _Active;
		
		private System.DateTime _create_dt;
		
		public sp_Timesheet_TimesheetID_getResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimesheetID", DbType="Int NOT NULL")]
		public int TimesheetID
		{
			get
			{
				return this._TimesheetID;
			}
			set
			{
				if ((this._TimesheetID != value))
				{
					this._TimesheetID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimesheetCompanyID", DbType="Int NOT NULL")]
		public int TimesheetCompanyID
		{
			get
			{
				return this._TimesheetCompanyID;
			}
			set
			{
				if ((this._TimesheetCompanyID != value))
				{
					this._TimesheetCompanyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimesheetInvoiceDate", DbType="DateTime NOT NULL")]
		public System.DateTime TimesheetInvoiceDate
		{
			get
			{
				return this._TimesheetInvoiceDate;
			}
			set
			{
				if ((this._TimesheetInvoiceDate != value))
				{
					this._TimesheetInvoiceDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimesheetInvoiceNumber", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TimesheetInvoiceNumber
		{
			get
			{
				return this._TimesheetInvoiceNumber;
			}
			set
			{
				if ((this._TimesheetInvoiceNumber != value))
				{
					this._TimesheetInvoiceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimesheetHourlyRate", DbType="Decimal(9,2) NOT NULL")]
		public decimal TimesheetHourlyRate
		{
			get
			{
				return this._TimesheetHourlyRate;
			}
			set
			{
				if ((this._TimesheetHourlyRate != value))
				{
					this._TimesheetHourlyRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimesheetStartDate", DbType="DateTime NOT NULL")]
		public System.DateTime TimesheetStartDate
		{
			get
			{
				return this._TimesheetStartDate;
			}
			set
			{
				if ((this._TimesheetStartDate != value))
				{
					this._TimesheetStartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimesheetEndDate", DbType="DateTime NOT NULL")]
		public System.DateTime TimesheetEndDate
		{
			get
			{
				return this._TimesheetEndDate;
			}
			set
			{
				if ((this._TimesheetEndDate != value))
				{
					this._TimesheetEndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimesheetHTML", DbType="VarChar(MAX)")]
		public string TimesheetHTML
		{
			get
			{
				return this._TimesheetHTML;
			}
			set
			{
				if ((this._TimesheetHTML != value))
				{
					this._TimesheetHTML = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_dt", DbType="DateTime NOT NULL")]
		public System.DateTime create_dt
		{
			get
			{
				return this._create_dt;
			}
			set
			{
				if ((this._create_dt != value))
				{
					this._create_dt = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
